### ISSUE TITLE
When going to advanced fields of the persons form consider the value inside 'Place of Birth / Marriage / Death' field as 'Place of Birth'

### ISSUE THREAD

**Issue by Inna-r** [Beit-Hatfutsot/dbs-front#364] opened 2017-05-08 14:10 UTC
Toggling 'show less/more fields' must toggle values inside 'Place of Birth / Marriage / Death' and 'Place of Birth' input fields (if one of these fields is filled)

**Comment by nuritgazit** [comment] 2017-05-15 09:23
@Inna-r @TheGrandVizier not sure I understand. Can you maybe add steps to reproduce?

**Comment by TheGrandVizier** [comment] 2017-05-15 09:27
1. Use advanced search with one of the fields described above
2. Go back to simple fields mode.

Result:
3 place fields are now merged to one.
Which value should be rwtaoned in the merged field given all 3 were full?


On May 15, 2017 12:23 PM, "Nurit" <notifications@github.com> wrote:

@Inna-r <https://github.com/inna-r> @TheGrandVizier
<https://github.com/thegrandvizier> not sure I understand. Can you maybe
add steps to reproduce?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Beit-Hatfutsot/dbs-front/issues/364#issuecomment-301422552>,
or mute the thread

**Comment by Inna-r** [comment] 2017-05-24 08:30
@nuritgazit @OriHoch 
### reproduce:
* go to general persons search
* fill 'place' input field with some value
* click 'more fields' (go to advanced search mode)
* Go back to simple fields mode

### expected (just like old persons search)
* 'place of birth' now contains the 'place' input field value
* 'place' input field gets back its value

My question is what is the meaning of 'place' field? old persons search considers 'place' as 'place of birth'. i think it has to be 'place of birth OR place of marriage OR place of death'. If so API must know how to handle 'place parameter'.

**Comment by nuritgazit** [comment] 2017-05-24 09:29
when searching for a place by using the "unified" field (in the simple search), the results should have all people who were either born or married or died in this place

**Comment by OriHoch** [comment] 2017-06-05 13:23
@Inna-r I don't understasnd what you mean by "API must know how to handle 'place parameter'"

in any case, this is purely frontend bug - need to decide how to handle it on the frontend, possible options:
(when switching from the advanced to simple place fields)
1. delete the existing values, and go back to empty place field
2. use the 1st value and use that for the combined place field

in any case, I think it's very low priority bug, not worth to include in high priority front IMO - @TheGrandVizier - up to you..

**Comment by OriHoch** [comment] 2017-06-05 13:32
@Inna-r opened a new issue with clear reproduction steps as I understood them
#411
please close this issue if it really handles your issue

**Closed** 2017-06-06 09:26 UTC
